name: "commit match test"
on:
  pull_request:
  push:
    branches: [main]

jobs:
  match:
    uses: ./.github/workflows/should-skip.yml
    with:
      patterns: "[skip test],[skip]"

  no-match:
    uses: ./.github/workflows/should-skip.yml
    with:
      patterns: "i'm good"

  verify1:
    runs-on: ubuntu-latest
    needs: match
    steps:
      - name: "Should match"
        run: |
          echo "Skip: ${{ needs.match.outputs.skip }}"
  verify2:
    runs-on: ubuntu-latest
    needs: no-match
    steps:
      - name: "Should not match"
        run: |
          echo "Skip: ${{ needs.no-match.outputs.match }}"
