name: "commit match test"
on:
  pull_request:
  push:
    branches: [main]

jobs:
  check1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Test 1"
        uses: ./.github/actions/commit-match.yml
        with:
          patterns: "[skip test]"

  check2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Test 1"
        uses: ./.github/actions/commit-match.yml
        with:
          patterns: "should not match"

  verify1:
    runs-on: ubuntu-latest
    needs: check1
    steps:
      - name: "Verify 1"
        run: |
          echo "Match: ${{ needs.check1.outputs.match }}"
          echo "Message: ${{ needs.check1.outputs.message }}"

  verify2:
    runs-on: ubuntu-latest
    needs: check2
    steps:
      - name: "Verify 2"
        run: |
          echo "Match: ${{ needs.check2.outputs.match }}"
          echo "Message: ${{ needs.check2.outputs.message }}"
