name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_output: ${{ steps.build_step.outputs.build_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build
        run: echo "Building the project..."
      - name: Set output for next job
        id: build_step
        run: echo "::set-output name=build_output::Build completed"
      - name: Debug - Show last commit
        run: |
          echo "Last commit message:"
          git log -1 --pretty=%B
          echo "Last commit SHA:"
          git log -1 --pretty=%H
          echo "PR HEAD SHA: ${{ github.event.pull_request.head.sha }}"
          echo "PR ms: ${{ github.event.pull_request.commits.*.message }}"

  e2e_tests:
    needs: build
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, '[skip e2e]') && !contains(join(github.event.pull_request.commits.*.message, ' '), '[skip e2e]')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use output from build job
        run: echo "Build output- ${{ needs.build.outputs.build_output }}"
      - name: Run E2E tests
        run: echo "Running end-to-end tests..."
