name: "Check Commit Message for Keywords"
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all PR-related commits are fetched
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout only the PR head commit
      - name: Get last commit message
        id: get_commit_message
        shell: bash
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            COMMIT_MESSAGE=$(git log -1 --no-merges ${{ github.event.pull_request.head.sha }} --pretty=format:"%s")
          else
            COMMIT_MESSAGE=$(git log --format=%B -n 1)
          fi
          echo "message<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Check if commit message contains any keyword
        id: check_commit
        shell: bash
        run: |
          match=false
          IFS=',' read -ra KEYWORDS <<< "[skip e2e],[skip]"
          for keyword in "${KEYWORDS[@]}"; do
            echo "Checking $keyword against $message"
            if [[ $message =~ "$keyword" ]]; then
               match=true
               echo "Match!"
               break
            fi
          done
          echo $match
          echo "match=$match" >> $GITHUB_OUTPUT
