# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: release

on:
  push:
    tags:
      - v*

jobs:
  get-tag-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Is prerelease
        id: is_prerelease
        env:
          PRERELEASE: ${{ contains(steps.get_tag.outputs.TAG, 'beta') || contains(steps.get_tag.outputs.TAG, 'alpha') }}
        run: echo ::set-output name=PRERELEASE::$PRERELEASE
      - name: Is beta
        id: is_beta
        env:
          BETA: ${{ contains(steps.get_tag.outputs.TAG, 'beta') }}
        run: echo ::set-output name=BETA::$BETA
      - name: Is alpha
        id: is_alpha
        env:
          ALPHA: ${{ contains(steps.get_tag.outputs.TAG, 'alpha') }}
        run: echo ::set-output name=ALPHA::$ALPHA
      - run: echo "Tag:" ${{steps.get_tag.outputs.TAG}}
      - run: echo "Prerelease:" ${{steps.is_prerelease.outputs.PRERELEASE}}
    outputs:
      alpha:  ${{ steps.is_prerelease.outputs.ALPHA }}
      beta:  ${{ steps.is_prerelease.outputs.BETA }}
      prerelease:  ${{ steps.is_prerelease.outputs.PRERELEASE }}
      current_tag:  ${{ steps.get_tag.outputs.TAG }}

  check:
    needs: [get-tag-info]
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - run: echo ${{needs.get-tag-info.outputs.alpha}}
      - run: echo ${{needs.get-tag-info.outputs.beta}}
      - run: echo ${{needs.get-tag-info.outputs.prerelease}}
      - run: echo ${{needs.get-tag-info.outputs.current_tag}}

#  build:
#    needs: [check]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 14.16
#      - run: git branch
#      - run: npm ci
#      - run: npm run build
#
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 14.16
#      - run: npm ci
#      - run: npm run test
#
  publish-npm:
    needs: [get-tag-info]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16
      - name: Publisch stable
        if: ${{!needs.get-tag-info.outputs.prerelease}}
        run: npm publish
      - name: Publisch alpha
        if: ${{needs.get-tag-info.outputs.alpha}}
        run: npm run publish-alpha
      - name: Publisch beta
        if: ${{!needs.get-tag-info.outputs.beta}}
        run: npm run publishBeta
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
#
#  create-release:
#    needs: [publish-npm, add-changelog]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Get tag
#        id: get_tag
#        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
#        shell: bash
#      - uses: actions/checkout@v1
#      - uses: ncipollo/release-action@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          prerelease: ${{ contains(steps.get_tag.outputs.TAG, 'beta') || contains(steps.get_tag.outputs.TAG, 'alpha') }}
