# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: release

# on:
#  push:
#    tags:
#      - v*

on: push
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16
      - run: npm ci
      - run: npm run test
      - run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    
  create-release:
    # needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
        env:
          IS_PRERELEASE: contains(steps.get_version.outputs.VERSION, 'beta') || contains(steps.get_version.outputs.VERSION, 'alpha')
      - run: echo ${{ env.IS_PRERELEASE }}      
      - run: echo ${{ steps.get_version.outputs.VERSION }}
      - uses: actions/checkout@v1
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ env.IS_PRERELEASE }}
