name: "commit match test"
on:
  workflow_call:
    inputs:
      patterns:
        type: string
        required: true
    outputs:
      skip:
        description: "Whether to skip the job"
        value: ${{ jobs.should-skip.outputs.skip }}
  push:
    branches: [main]

jobs:
  should-skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/commit-match
        id: commit-match
        with:
          patterns: ${{ inputs.patterns }}
      - id: skip
        run: echo "skip=${{ steps.commit-match.outputs.match }}" >> $GITHUB_OUTPUT
